import os

PROJECT_ID = os.getenv("PROJECT_ID")
INSTANCE_CONNECTION_NAME = os.getenv("INSTANCE_CONNECTION_NAME")
BUCKET_NAME = os.getenv("BUCKET_NAME")
GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
DB_PASSWORD = os.getenv("DB_PASSWORD")
